name: Generate DOCX and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  generate_and_upload:
    if: contains(github.event.head_commit.message, '-gen')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx

      - name: Run extraction script
        run: |
          python extract_files.py

      - name: Upload DOCX file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-docx
          path: output.docx
